name: Delete Unchanged Files
on:
  pull_request:
    types: [closed]  # Runs when a PR is merged
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Source Branch
        run: |
          # Define allowed branch
          ALLOWED_BRANCH="translation-source-control" 
          # Get the source branch of the PR
          PR_BRANCH="${{ github.head_ref }}"
          echo "PR opened from branch: $PR_BRANCH"
          # Exit if the PR is not from the allowed branch
          if [[ "$PR_BRANCH" != "$ALLOWED_BRANCH" ]]; then
            echo "This PR is not from $ALLOWED_BRANCH. Exiting..."
            echo "SKIP_JOB=true" >> $GITHUB_ENV
          fi
      - name: Checkout repository
        if: env.SKIP_JOB != 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate diff
      
      - name: Identify and Remove Unchanged Files
        if: env.SKIP_JOB != 'true'
        run: |
          # Defining the folders to check
          JA="ja"
          ZH="zh-Hans"
          # Getting list of updated files in the last PR (
          UPDATED_FILES=$(git diff --name-only HEAD^ HEAD -- "$JA" "$ZH")
          #Check if there are updated files, if not do not make changes
          if [[ -z "$UPDATED_FILES" ]]; then
            echo "no updated files detected, Exiting..."
            exit 0
          fi
          echo "Updated Files: "
          echo "$UPDATED_FILES" 
          # Get all HTML files in subdirectories
          ALL_HTML_FILES=$(find "$JA" "$ZH" -type f -name "*.html")
          # Loop through all HTML files and delete those that were NOT updated
          for file in $ALL_HTML_FILES; do
            if ! echo "$UPDATED_FILES" | grep -q "$file"; then
              echo "Deleting: $file"
              rm "$file"
            fi
          done
      
      - name: Commit and Push Changes
        if: env.SKIP_JOB != 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Cleanup: Remove non-updated HTML files" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
